name : Hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world steps
        run: |
          echo "this is first line"
          echo "this is second line "
          

